### ISSUE TITLE
something is wrong with buildDescriptionIcon

### ISSUE THREAD

**Issue by SxMShaDoW** [SxMShaDoW/embeddable-badges-plugin#46]
> ` WARNING: Error while serving http://localhost:8080/buildStatus/buildDescriptionIcon
> java.lang.reflect.InvocationTargetException
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:320)
>   at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:163)
>   at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
>   at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
>   at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
>   at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
>   at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
>   at org.kohsuke.stapler.MetaClass$11.dispatch(MetaClass.java:380)
>   at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
>   at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
>   at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
>   at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
>   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
>   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
>   at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
>   at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
>   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
>   at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
>   at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
>   at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
>   at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
>   at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
>   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
>   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
>   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
>   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
>   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
>   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
>   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
>   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
>   at org.eclipse.jetty.server.Server.handle(Server.java:370)
>   at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
>   at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
>   at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
>   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
>   at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
>   at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
>   at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
>   at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
>   at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NullPointerException
>   at org.jenkinsci.plugins.badge.ImageResolver.replaceBuildDescriptionSVG(ImageResolver.java:300)
>   at org.jenkinsci.plugins.badge.ImageResolver.getBuildDescriptionImage(ImageResolver.java:337)
>   at org.jenkinsci.plugins.badge.PublicBadgeAction.doBuildDescriptionIcon(PublicBadgeAction.java:218)
>   ... 57 more
> 
> Jul 03, 2016 3:28:10 AM org.eclipse.jetty.util.log.JavaUtilLog warn
> WARNING: Error while serving http://localhost:8080/buildStatus/buildDescriptionIcon
> java.lang.reflect.InvocationTargetException
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:320)
>   at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:163)
>   at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
>   at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:124)
>   at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
>   at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
>   at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
>   at org.kohsuke.stapler.MetaClass$11.dispatch(MetaClass.java:380)
>   at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
>   at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
>   at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
>   at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
>   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
>   at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
>   at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
>   at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
>   at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
>   at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
>   at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
>   at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
>   at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
>   at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
>   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
>   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
>   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
>   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
>   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
>   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
>   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
>   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
>   at org.eclipse.jetty.server.Server.handle(Server.java:370)
>   at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
>   at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
>   at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
>   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
>   at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
>   at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
>   at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
>   at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
>   at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.NullPointerException
>   at org.jenkinsci.plugins.badge.ImageResolver.replaceBuildDescriptionSVG(ImageResolver.java:300)
>   at org.jenkinsci.plugins.badge.ImageResolver.getBuildDescriptionImage(ImageResolver.java:337)
>   at org.jenkinsci.plugins.badge.PublicBadgeAction.doBuildDescriptionIcon(PublicBadgeAction.java:218)
>   ... 57 more ``

**Comment by SxMShaDoW** [comment]
this has been fixed in 2.5.2
